### ISSUE TITLE
no information for database

### ISSUE THREAD

**Issue by yaboibutt3r** [VORPCORE/vorp_crawfish#5]
I am new so it could just be user error not necessarily a issue but there's no sql file in the script itself so it causes a error. I know all I have to do is create a sql line in the database but I don't really know how to. This is not a complaint just more of a suggestion for making installation smoother for dummy's like myself

**Comment by outsider31000** [comment]
there is no sql needed. this script does not need one

**Comment by yaboibutt3r** [comment]
hm I must be dumb or something cause I have a item animal__crawfish missing from my database and I assumed it was for this script.. must be something else, anyways I appreciate the help

**Comment by outsider31000** [comment]
you need to add the item. its one item sql for one item its not needed. ask for help in the discord if you need.
